--chave primaria e estrangeira
--constraint

--chave estrangeira
--referencia

--CREATE TABLE
--not null
--unique
--primary key
--foreign key
--check
--default

CREATE TABLE Canal (
CanalID int Primary Key,
Nome varchar(150) not null,
ContagemInscritos int DEFAULT 0,
DataCriacao DATETIME NOT NULL
);

SELECT * FROM Canal;

CREATE TABLE VIDEO(
VideoID INT PRIMARY KEY,
Nome VARCHAR(150) NOT NULL,
VISUALIZACOES INT DEFAULT 0,
LIKES INT DEFAULT 0,
DISLIKES INT DEFAULT 0,
DURACAO INT NOT NULL,
CanalID INT FOREIGN KEY REFERENCES Canal(CanalID)
);

SELECT * FROM VIDEO;

CREATE TABLE LOCAL(
CEP INT PRIMARY KEY,
RUA VARCHAR(150) NOT NULL,
ESTADO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL
);

CREATE TABLE PESSOA(
CPF INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
CEP INT FOREIGN KEY REFERENCES Local(CEP)
);