--DATEPART
SELECT SalesOrderID, DATEPART(MONTH, OrderDATE) AS MES
FROM Sales.SalesOrderHeader;

--DATEPART SQL SERVER NO GOOGLE

SELECT avg(TotalDue) MEDIA, DATEPART(MONTH, OrderDate) AS MES
FROM Sales.SalesOrderHeader
GROUP BY DATEPART (MONTH, ORDERDATE)
ORDER BY MES;

SELECT avg(TotalDue) MEDIA, DATEPART(YEAR, OrderDate) AS ANO
FROM Sales.SalesOrderHeader
GROUP BY DATEPART (YEAR, ORDERDATE)
ORDER BY ANO;

SELECT avg(TotalDue) MEDIA, DATEPART(DAY, OrderDate) AS DAY
FROM Sales.SalesOrderHeader
GROUP BY DATEPART (DAY, ORDERDATE)
ORDER BY DAY;


