CREATE TABLE NETFLIX(
ID INT PRIMARY KEY,
NOME VARCHAR(150) NOT NULL UNIQUE,
CATEGORIA VARCHAR(200) NOT NULL,
LANCAMENTO DATETIME NOT NULL
)

SELECT * FROM NETFLIX

ALTER TABLE NETFLIX
ADD ATIVO bit

ALTER TABLE NETFLIX
ALTER COLUMN CATEGORIA VARCHAR(150) NOT NULL

